### ISSUE TITLE
Bot for viewing and updating OKR in the service gtmhub.com

### ISSUE THREAD

**Issue by Maay** [dialogs/dialog-okr-bot#1] opened 2019-03-26 18:24 UTC
We are the team of corporate messenger dialog. We have Java/Python/JavaScript Bot SDK to create bots in our messenger. Since it is new, we want to develop several bots with the help of the community for everyday use.

The documentation of our Java Bot SDK is here: https://docs.dlg.im/bots/java-bot.html

The documentation of our Python Bot SDK is here: https://dialogs.github.io/python-bot-sdk/ ⁣ ⁣ ⁣

The documentation of our JavaScript Bot SDK is here: https://dialogs.github.io/js-bot-sdk/

We'd prefer to use Python or JS SDK.

Our messenger has a test instance. Web client that you should use for the development is available here: https://grpc-test.transmit.im/

For web use this endpoint: https://grpc-test.transmit.im:8443
For bots use grpc endpoint: https://grpc-test.transmit.im:9443
Test accounts:
`alice` / `password`
After you've logged in you should write to `Security Bot` user (you can find him in the search field) and write command `/bot new bot_username bot_name` where `bot_username` is the username you can choose for your new bot and `bot_name` is his display name

We've open-sourced several bots that you can look up to for examples https://github.com/dialogs?utf8=%E2%9C%93&q=-bot&type=&language=

Please feel free to ask questions in our community https://dlg.im/@botsfordialog ⁣ ⁣

**This bot is for viewing and updating OKR in the service gtmhub.com**

1) Bot config should be managed from a text config file. In the config file, we specify data for integration with gtmhub.com. The author login in gtmhub.com and dialog is the same.
2.1) The user writes the bot in personal chat `My OKR [list_name]`. 
2.2) The bot sends the user his OKRs from the specified list in the message in this format:
```
[Objective 1](link_to_objective) - completion percentage
[Title of the key result](link to the key result) - value - * percentage of completion * - "Refresh" button
...
[Title of the key result](link to the key result) - value - * percentage of completion * - "Refresh" button

...

[Objective X](link_to_objective) - completion percentage
[Title of the key result](link to the key result) - value - * percentage of completion * - "Refresh" button
...
[Title of the key result](link to the key result) - value - * percentage of completion * - "Refresh" button
```

3.1) The user writes the bot in the private chat "OKR @username [list_name]"
3.2) The bot sends OKRs of specified user from the specified list in the message in the format:
```
[Objective 1](link_to_objective) - completion percentage
[Title of the key result](link to the key result) - value - * percentage of completion * - "Refresh" button
...
[Title of the key result](link to the key result) - value - * percentage of completion * - "Refresh" button

...

[Objective X](link_to_objective) - completion percentage
[Title of the key result](link to the key result) - value - * percentage of completion * - "Refresh" button
...
[Title of the key result](link to the key result) - value - * percentage of completion * - "Refresh" button
```
4.1) User clicks on “Refresh” in one of his key results.
4.2) The bot sends the user a message in the format:
```
The title of the key result
Now - * current_value_key_search_ result *
Must be - * key_result target_value *
Specify a new value.
```
4.3) The user sends a numeric value. If the value does not fit the format, the bot asks to send the correct value.
4.4) The bot sends the user a message in the format: `What has changed? Why?`
4.5) The user sends any text message.
4.6) The bot sends a message to the user in the format: "Specify the level of confidence in the result [dropdown_to_all_confidence_options]"
4.7) The user selects the result
4.8) The bot sends the user a message in the format:
```
[Key result](link to key result) - new completion percentage
Submit button, Cancel button
```
4.9.1) The user selects "send" and the bot sends new values to gtmhub.
4.9.2) The bot sends the user a message: "The result is updated"
4.10.1) The user selects "Cancel" and the bot resets all fields. At any previous stage, the user instead of pressing the button can send "/stop" and reset the process.
4.10.1) The bot sends the user a message "The update has been cancelled"

This is one of the features that this bot has. Look up other issues in this repo for other features. Each feature can be developed in separate bots (even in different languages but with the same name) using the same token. But, in case of a private chat with a bot, you have to add a check that peer id is equal to sender id in incoming SeqUpdate params. It’s needed to prevent the feature’s mutual influence. For example(Python):

```
def on_msg1(*params):
    if params[0].peer.id == params[0].sender_uid:  # this prevents false reactions 
        bot1.messaging.send_message(
            …
        )
```

For bounty to be verified, it’s necessary to create documentation for it.

**Comment by willy2dg** [comment] 2019-03-28 01:26
I will take a look.

**Comment by willy2dg** [comment] 2019-04-01 19:22
Hi @Maay , since you prefered JS or Pyhton SDK to solve the issue i am trying to get working the JS example. But using CommonJs or diferent presets with Babel i get "bot.onMessage is not a function", for the last job i was getting the same results, and i can't found the onMessage function. How i can get the example working ?? I am looking in other bots to get an idea, but i would appreciate some tip .

**Comment by willy2dg** [comment] 2019-04-03 04:37
Finally i moved to python, so you can omit the last message. Anyways could be nice to know.

Could you provide me a test user on gtmhub? I tryed do it be my self but they whant a corporative email ( does not accept gmail ) and mobile phone number ( which currently i don't have ).

**Comment by Drymonade** [comment] 2019-04-08 12:05
@willy2dg Hi there! Sorry for the delay. To sign in go to https://dialog-test.us.gtmhub.com/join and use following credentials: 

Email: testbot@dlg.im
Password: KaMwoBiR1749

**Comment by willy2dg** [comment] 2019-04-08 12:26
@Drymonade No problem, I've been advancing what I could, thanks a lot for your help.

**Comment by willy2dg** [comment] 2019-04-08 12:31
I changed the password just in case, i will give you back the credentials to test i tell me if you need it before .

**Comment by Drymonade** [comment] 2019-04-11 07:36
@willy2dg 
Try this one: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1NTQ5MTM2NjQsInN1YiI6ImF1dGgwfDVjYWIzMzkxZTIyYzRiMGViYzdjY2FjMyJ9.-gg8YFzQm_7U0odVm4CmzzHJMnAjnzQCEUv8NTNELIk

**Comment by willy2dg** [comment] 2019-04-11 12:56
@Drymonade sorry, but i need the Account ID too, the location is provided in the same link.

**Comment by Drymonade** [comment] 2019-04-11 14:54
@willy2dg 
Try this one: 5cab1dec899aa4000140b93f

**Comment by willy2dg** [comment] 2019-04-11 15:37
Thanks, but it says "account not found" i am not sure if it is related to the token config or whats failing, i will contact the support to be sure, while i still looking at. Sorry for this inconveniences.

**Comment by willy2dg** [comment] 2019-04-11 17:13
Ok, looks there was diferent URL's for US/EU accounts, and looks working now :) Talk you soon.

**Comment by willy2dg** [comment] 2019-04-11 23:35
@Drymonade i clean my cookies and looks some one changed the password for the dialogs test user ( alice / password )

**Comment by Drymonade** [comment] 2019-04-12 06:01
@willy2dg You can use bobby / password

**Comment by willy2dg** [comment] 2019-04-12 12:28
@Drymonade can't login, i open https://grpc-test.transmit.im, setting up https://grpc-test.transmit.im:8443 as server and used the credentials, but throws "Password and login mismatched". Not sure if some one change the password or whats happening :(

**Comment by Drymonade** [comment] 2019-04-12 14:03
@willy2dg It's fixed for Alice. Now alice / password works.

**Comment by willy2dg** [comment] 2019-04-12 14:04
thanks @Drymonade , now is working again :) all ready now and hope no more problems

**Comment by willy2dg** [comment] 2019-04-16 06:13
Hi @Maay, Is there a problem if I slightly change the format of the commands? The "list_name" parameter ( on point 2.1 and 3.1 ) makes referense to "sessions" on the gtmhub API?
I'm a bit lost with that concept but the bot is almost finished, I hope to send PR later or tomorrow.

**Comment by Maay** [comment] 2019-04-17 10:40
@willy2dg it would be ok! Yes, list's and sessions are the same things.

**Comment by willy2dg** [comment] 2019-04-20 12:43
Hi @Maay, i sent a PR.

**Comment by Drymonade** [comment] 2019-04-20 15:23
@willy2dg Hi, we will check it soon, stay tuned!

**Comment by Drymonade** [comment] 2019-05-08 15:26
@willy2dg I tried to launch it:
```
dialog-okr-bot $ python3 gtmhub_bot.py
Traceback (most recent call last):
  File "gtmhub_bot.py", line 181, in <module>
    handler = GtmHubMetricHandler(gtmhub_config['url'], gtmhub_config['token'], gtmhub_config['account'])
  File "/Users/skiba/dialog-okr-bot/gtmhub_metric_handler.py", line 10, in __init__
    self.users = self.api.list_users()['items']
  File "/Users/skiba/dialog-okr-bot/gtmhub_api.py", line 16, in list_users
    return response.json()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Configs seems to be correct.

**Comment by willy2dg** [comment] 2019-05-08 16:02
Hello, @Drymonade, are you using the test configuration? The GtmHub test account was expired, so it can cause malformed API responses (not JSON responses), if this is the case, try another GtmHub account.

Anyway, I'll check it and handle it to throw a friendlier error.

**Comment by willy2dg** [comment] 2019-05-09 00:58
PR updated to wrap the error.

**Comment by willy2dg** [comment] 2019-05-20 01:52
Hello @Drymonade , could you take a look?

**Comment by Drymonade** [comment] 2019-05-21 12:20
@willy2dg Thanks a lot for patience, I'll return with feedback on this week, stay tuned!

**Comment by Drymonade** [comment] 2019-05-24 08:21
@willy2dg Now we are on this issue: 
```
dialog-okr-bot $ python3 gtmhub_bot.py
Error initializing the bot - HTTPSConnectionPool(host='dlgim.gtmhub.com', port=443): Max retries exceeded with url: /api/v1/assignees (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1097ad160>: Failed to establish a new connection: [Errno 61] Connection refused'))
```

**Comment by Drymonade** [comment] 2019-05-24 08:24
@willy2dg Now we are on this issue:
```
dialog-okr-bot $ python3 gtmhub_bot.py
Error initializing the bot - GtmHub error response "<!DOCTYPE html><html><head><title>Gtmhub</title><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"><link href="/dist/css/login.css" rel="stylesheet"></head><body><div id="login-background"></div><div id="error-message"><h1>The page you are looking for doesn't exist.</h1><h2>But you can try to log in again from <a href="/login">here</a> or create a new account from <a href="/sign-up">here</a>.</h2></div><script>window.intercomSettings = {
  app_id: "yh2j9u8r"
};
</script><script>(function(){var w=window;var ic=w.Intercom;if(typeof ic==="function"){ic('reattach_activator');ic('update',intercomSettings);}else{var d=document;var i=function(){i.c(arguments)};i.q=[];i.c=function(args){i.q.push(args)};w.Intercom=i;function l(){var s=d.createElement('script');s.type='text/javascript';s.async=true;s.src='https://widget.intercom.io/widget/yh2j9u8r';var x=d.getElementsByTagName('script')[0];x.parentNode.insertBefore(s,x);}if(w.attachEvent){w.attachEvent('onload',l);}else{w.addEventListener('load',l,false);}}})()</script></body></html>" with code : 404
dialog-okr-bot $
```

**Comment by willy2dg** [comment] 2019-05-24 10:47
Looks strange, the calls to the API could return a JSON or plain text. Are you using a valid URL for the API ?("https://app.us.gtmhub.com/api/v1" or "https://app.gtmhub.com/api/v1", i think yours will be the first one)

**Comment by willy2dg** [comment] 2019-05-24 12:42
@Drymonade I updated the PR throwing the exceptions again to have more info to debug since i can't reproduce the error and seems isn't an API response.

**Comment by willy2dg** [comment] 2019-05-28 11:37
@Drymonade can you check it again , please .

**Comment by Drymonade** [comment] 2019-05-28 12:46
@willy2dg Sorry for the delay, your patience is awesome :) Bot starts properly, but there are no reaction on `/okr` command in chat. And every username that I type like `/okr [[a.skiba]]` produces `Invalid username` message.

**Comment by willy2dg** [comment] 2019-05-28 13:04
Thanks @Drymonade there are no rushes, but could be nice if we keep going. I think it is because the name doesn't match exactly, the API return a full name format instead of username, we can print the available names on fail if you want ( can be done for sessions too ) . If the GtmHub account haven't enoght permissions it can returns a empty list, but i think is not the case. Wait for your news .

**Comment by willy2dg** [comment] 2019-05-29 03:48
@Drymonade changes done.

**Comment by Drymonade** [comment] 2019-05-29 10:46
@willy2dg There are still no reaction on messages
![Снимок экрана 2019-05-29 в 13 45 45](https://user-images.githubusercontent.com/15854870/58551195-2c906f80-8218-11e9-8e07-12a009af59c0.png)

**Comment by willy2dg** [comment] 2019-05-29 12:34
@Drymonade this no reactions seems a empty list of OKR, i will add a message for that, but have the bot enough permission to see these OKR's ?? There is some exception on the bot ?? Sorry for that, I am reviewing it, but i can't test it directly right now, since the account was expired.

**Comment by Drymonade** [comment] 2019-05-29 12:39
@willy2dg It might be the case, but there is an API token personally for my account and it is supposed for the bot to see at least my OKR's :) OK, I will check the permissions once again.

**Comment by willy2dg** [comment] 2019-05-29 12:43
@Drymonade can you test it with no parameters ? Just "/okr", just to know if it returns your OKR's.

**Comment by Drymonade** [comment] 2019-05-29 12:55
@willy2dg It returns nothing, and no response in chat.

**Comment by willy2dg** [comment] 2019-05-29 13:32
Thanks for your fast response @Drymonade, then seems there is some permission issue involved ( i can't be more specific because it was configured for the testing account ) because it was working for sure. We should before verify the "/okr" command if it isn't working, since the other options add filters to the same query. Please take a look to the permissions and ensure you have some OKR's created on your account ( which is assigned to the GtmHub token )

**Comment by willy2dg** [comment] 2019-05-29 13:38
I added a message in case the API returns an empty list, not a fix, just to give some feedback in this case. I hope some news.

**Comment by willy2dg** [comment] 2019-05-29 14:15
My apologies @Drymonade , I have noticed that they have updated the session filter, so currently it was returning the OKRs which isn't assigned to a session. I updated the default value to the session filter and i hope it will work again, i will wait for your feedback :)

**Comment by Drymonade** [comment] 2019-05-29 15:14
@willy2dg Yeah, your last change do the trick! I can see my OKR's, but can't refresh it:
![Снимок экрана 2019-05-29 в 18 14 05](https://user-images.githubusercontent.com/15854870/58568819-953e1300-823d-11e9-822b-2270e1659135.png)

**Comment by Drymonade** [comment] 2019-05-29 15:15
@willy2dg Some info from console:
```
dialog-okr-bot $ python3 gtmhub_bot.py
Bot is ready.
'confidence'
'confidence'
```

**Comment by willy2dg** [comment] 2019-05-29 16:53
@Drymonade Glad to hear these first problem was fixed. The new issue its because the API is not returning the "confidence" field for the specified metric. But i am not sure about the reason since the field still on the API with no annotations and was working before. I'll check it and tell you something

**Comment by willy2dg** [comment] 2019-05-29 17:56
@Drymonade seems they are adding features to the platform ( [eg. custom confidence configuration](https://help.gtmhub.com/okrs/intermediate/confidence-scaling) ) and provably something changed. I writed to the support and i am waiting for some response. Meanwhile could be nice if you can ensure your "confidence" configuration is "0 to 1" or "0 to 0.1" which was the available before.

**Comment by Drymonade** [comment] 2019-05-30 11:51
@willy2dg 
<img width="930" alt="Снимок экрана 2019-05-30 в 14 49 19" src="https://user-images.githubusercontent.com/15854870/58631165-531edb00-82ea-11e9-9317-ee05b1974cdd.png">

**Comment by willy2dg** [comment] 2019-05-30 13:23
Hi @Drymonade, from the support, they answered this field is not returned because its not already introduced. So i will add a check for that and will be fixed. Then the problem there is we can't get the confidence scale from this value and can't be checked from the API, the support says the API is using a single scale ( 0 to 1 ) and the value is displayed on the website using the configured scale. So its ok if  we use this single scale for the confidence value ?

If you agree I will implement this and talk to you.

**Comment by Drymonade** [comment] 2019-05-30 14:35
@willy2dg Yeah, it's OK.

**Comment by willy2dg** [comment] 2019-05-30 22:36
@Drymonade pushed some changes.

**Comment by Drymonade** [comment] 2019-05-31 13:37
@willy2dg It quite works! Awesome! There is an error at last step (submitting final score):
```
GtmHub error response "json: cannot unmarshal string into Go struct field CheckInMetricRequest.confidence of type float64"with code : 400
```

**Comment by willy2dg** [comment] 2019-06-01 02:47
@Drymonade Nice !! I has an error there, i think is fixed now and should work properly :)

**Comment by willy2dg** [comment] 2019-06-04 09:58
@Drymonade Is it working properly?

**Comment by Drymonade** [comment] 2019-06-04 10:05
@willy2dg We have some issues in our infrastructure now, I'll return with response in a few hours.

**Comment by Drymonade** [comment] 2019-06-04 10:17
@willy2dg Yes, all is correct. Last thing before closing this bounty - can you prevent bot from reacting on group messages? It should only works in private dialogs. This is important because we have autojoin in some groups and bots are being auto-joined too, so they reacts on messages in groups.

**Comment by willy2dg** [comment] 2019-06-04 10:27
Sure @Drymonade, i will update the PR now.

**Comment by willy2dg** [comment] 2019-06-04 10:49
@Drymonade I sent a update. Can we close the issue ?

**Comment by Drymonade** [comment] 2019-06-04 11:46
@willy2dg Yeah, now it's perfect. Thanks a lot for your work and sorry for our delays! It would be nice to work with you on our future bounties! I'm closing now this issue.

**Closed by Drymonade** 2019-06-04 11:46 UTC

**Comment by willy2dg** [comment] 2019-06-04 12:33
Thanks @Drymonade, it will be a pleasure to work with you again. I already sent a bounty claim, best regards, Willy
